site_name: Center for Computational Mathematics
 University of Colorado Denver 
site_url: https://ccm-docs.readthedocs.io/en/latest/ 
repo_url: https://github.com/ccmucdenver/ccm-docs 
edit_uri: edit/main/docs/
site_description: Documentation for computing resources at the CCM
theme:
  name: readthedocs
  highlightjs: true
  features:
    - navigation.instant
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
    - Home: index.md
    - News and status: updates.md
    - Overview: overview.md
    - Clusters Guide: clusters_guide.md
    - Examples: examples.md
    - Accounts and Allocations: accounts.md
    - Python: python.md
    - Environment modules: modules.md
    - Alderaan Cluster: alderaan.md
    - Colibri Cluster: colibri.md
    - Score Cluster: score.md
    - Research Storage: storage.md
    - Singularity Containers: singularity.md
    - JupyterHub Server: jupyterhub.md
    - Local network: local.md
    - External Resources: external.md
    - Facilities, Equipment, and Other Resources: facilities.md
